PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?uri_type ?name WHERE {
    ?uri a ?uri_type.
    OPTIONAL {?uri_type rdfs:label ?name}
}